User registration
scoiatael/zosia16-site pull request #10
Opened 2016-11-13 20:45 UTC by scoiatael

2016-11-14 14:58 UTC, szewczykmira requested changes

2016-11-14 14:58 UTC, szewczykmira commented on users/actions.py
> +        from django.template import loader
zgodnie z pep8 importy powinny być na początku pliku: 

> Imports are always put at the top of the file, just after any module comments and docstrings, and before module globals and constants.

Dodatkowo jeżeli importy są w funkcji to jej wykonanie zajmuje więcej czasu - za każdym wywołaniem musi je wykonać.

2016-11-14 14:58 UTC, szewczykmira commented on users/actions.py
> +        from django.utils.encoding import force_text
jak wyżej

2016-11-14 14:58 UTC, szewczykmira commented on users/forms.py
> +        user.is_active = False
można też ustawić w userze, że is_active z automatu jest False

2016-11-14 14:58 UTC, szewczykmira commented on users/views.py
> +    form = forms.UserForm(request.POST)
`request.POST or None` - nie będziesz miał na wstępie przy użyciu geta walidacji danych których nawet jeszcze nie dostałeś.

2016-11-14 14:58 UTC, szewczykmira commented on users/views.py
> +    if request.method == 'GET' or not form.is_valid():
lepiej by było zrobić if `request.method == 'POST'` i pod tym wrzucić rzeczy które wykonują się kiedy request jest postem

2016-11-14 14:58 UTC, szewczykmira commented on users/views.py
> +def activate(request, uidb64, token):
jeżeli ten request jest postem to przydałoby się sprawdzić czy rzeczywiście przychodzi post :)

2016-11-14 21:26 UTC, scoiatael commented on users/views.py
> +def activate(request, uidb64, token):
to bedzie raczej GET -> podobnie jak https://github.com/django/django/blob/master/django/contrib/auth/views.py#L310 . nie jest do konca RESTful ale chyba nie da sie ladnie wyslac userowi linka ktory bylby otwarty POSTem po kliknieciu ;)

2016-11-15 18:23 UTC, szewczykmira reviewed
Generalnie jedna mała poprawka i będzie super :)

2016-11-15 18:23 UTC, szewczykmira commented on users/forms.py
> +        user.set_password(self.cleaned_data['password'])
tak sobie pomyślałam to może powinniśmy rozważyć pole confirm password :)

2016-11-15 18:23 UTC, szewczykmira commented on users/forms.py
> +        self.user = user
w modelForm zawsze zwraca obiekt, przydałoby się tak też i tutaj zrobić.

2016-11-15 18:23 UTC, szewczykmira commented on users/views.py
> +            user = form.save(request)
taaaa, przecież `form.save()` na pewno będzie czymś innym niż `None` :)

2016-11-19 17:52 UTC, scoiatael commented on users/forms.py
> +        self.user = user
Zrobione - zostawiam to pole user tylko po to zeby nie musiec zmieniac `context` w odpowiedzi.

2016-11-19 17:59 UTC, szewczykmira approved these changes

2016-11-19 18:32 UTC, merged