Added Place migration, unit tests
scoiatael/zosia16-site pull request #3
Opened 2016-10-19 20:20 UTC by scoiatael

2016-10-22 19:01 UTC, szewczykmira requested changes

2016-10-22 19:01 UTC, szewczykmira commented on Makefile
> +	python ./manage.py test --settings=zosia16.settings.test
Uwaga: teoretycznie to jest dobre, ale tak czy inaczej najpierw wykona się plik settings z `manage.py` a dopiero potem ten `zosia16.settings.test`. Czyli może pojawić się gdzieś przy odpalaniu testów błąd w stylu `cannot connect to database` bo ktoś nie będzie miał odpalonego postgresa :)

2016-10-22 19:01 UTC, szewczykmira commented on conferences/models.py
> +        blank=True
Zamiast  `CharField` możesz użyć `URLField` - załatwia to problem walidacji czy pole zawiera poprawną wartość dla urla

2016-10-22 19:01 UTC, szewczykmira commented on conferences/models.py
> +    def find_active():
Może przerzucimy to do managera? Bo w tym momencie potrzebujemy instancję obiektu, żeby z tego skorzystać. 
Brak `self`

2016-10-23 17:54 UTC, scoiatael commented on Makefile
> +	python ./manage.py test --settings=zosia16.settings.test
Nope.

2016-10-23 17:56 UTC, scoiatael commented on conferences/models.py
> +        blank=True
Done.

2016-10-23 17:56 UTC, scoiatael commented on conferences/models.py
> +    def find_active():
Brakowało `@staticmethod` ;) Zmienione na metodę managera.

2016-10-23 17:59 UTC, closed without merging